<a href="https://colab.research.google.com/github/kr-sarthak/Intro-to-ML-NLP/blob/main/Assisngment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Random function
arr = np.random.randint(1, 50, (5, 4))
print("Array:\n", arr,"\n")

# Anti-diagonal elements (from top-right to bottom-left)
anti_diag = [int(arr[i, -1 - i]) for i in range(min(arr.shape))]
print("Anti-diagonal elements:", anti_diag ,"\n")

# Max in each row
max_rows = np.max(arr, axis=1)
print("Max in each row:", max_rows, "\n")


# Elements less than or equal to mean
mean_val = np.mean(arr)
filtered_arr = arr[arr <= mean_val]
print("Elements <= mean (", mean_val, "):", "\n",filtered_arr,"\n")

# Boundary traversal function
def numpy_boundary_traversal(matrix):
    result = []
    rows, cols = matrix.shape


    result.extend(matrix[0]) # Top row

    result.extend(matrix[1:rows-1, -1]) # Right column

    result.extend(matrix[-1][::-1]) # Bottom row (reversed)

    result.extend(matrix[rows-2:0:-1, 0]) # Left column (reversed)

    return result

print("Boundary traversal:", [int(x) for x in numpy_boundary_traversal(arr)])


Array:
 [[18 45 14 19]
 [ 6 42 46  4]
 [ 3 13 11 39]
 [14 42  3 35]
 [28 16  5 31]] 

Anti-diagonal elements: [19, 46, 13, 14] 

Max in each row: [45 46 39 42 31] 

Elements <= mean ( 21.7 ): 
 [18 14 19  6  4  3 13 11 14  3 16  5] 

Boundary traversal: [18, 45, 14, 19, 4, 39, 35, 31, 5, 16, 28, 14, 3, 6]


In [ ]:
# Generate 1D array of float
arr = np.random.uniform(0, 10, 20)
arr = np.round(arr, 2)
print("Rounded Array:", arr,"\n")

# Print central Tendency
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Median:", np.median(arr),"\n")

# Replace elements < 5 with their squares
arr_modified = np.where(arr < 5, np.round(arr**2, 2), arr)
print("Modified Array:", arr_modified,"\n")

# Alternate sort
def numpy_alternate_sort(array):
    sorted_arr = np.sort(array)
    result = []
    left, right = 0, len(array) - 1
    toggle = True

    while left <= right:
        if toggle:
            result.append(sorted_arr[left])
            left += 1
        else:
            result.append(sorted_arr[right])
            right -= 1
        toggle = not toggle

    return np.array(result)

print("Alternate Sorted Array:", numpy_alternate_sort(arr))


Rounded Array: [1.05 2.16 1.61 2.52 8.27 2.81 4.76 3.52 7.4  8.09 6.69 0.17 0.47 9.25
 8.52 0.69 4.14 7.33 7.07 9.1 ] 

Min: 0.17
Max: 9.25
Median: 4.449999999999999 

Modified Array: [ 1.1   4.67  2.59  6.35  8.27  7.9  22.66 12.39  7.4   8.09  6.69  0.03
  0.22  9.25  8.52  0.48 17.14  7.33  7.07  9.1 ] 

Alternate Sorted Array: [0.17 9.25 0.47 9.1  0.69 8.52 1.05 8.27 1.61 8.09 2.16 7.4  2.52 7.33
 2.81 7.07 3.52 6.69 4.14 4.76]


In [ ]:
import pandas as pd
import numpy as np

#Student names and subjects
names = ['Abhi', 'Gagan', 'Lakshmi', 'Ras', 'Vishu', 'Shivteja', 'Molly', 'Dev', 'Kumar', 'Vengla']
subjects = ['Maths', 'Pharmacology', 'CS', 'Phsycology', 'Physiology', 'Medicine', 'Chemistry', 'Physics', 'Biology', 'Mechanics']

#Generate random marks (50–100) for each student and each subject
marks = {subject: np.random.randint(50, 101, size=len(names)) for subject in subjects}
df = pd.DataFrame(marks)
df.insert(0, 'Name', names)

#Compute total and scaled score (out of 100)
df['Total'] = df[subjects].sum(axis=1)
df['Scaled Score'] = (df['Total'] / (len(subjects) * 100)) * 100

#Assign Grade based on scaled score
def assign_final_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'

df['Grade'] = df['Scaled Score'].apply(assign_final_grade)

#Sort by Score descending
sorted_df = df.sort_values(by='Scaled Score', ascending=False)

#Average score for each subject
subject_avg = df[subjects].mean().round(2)

#Function to return students with grade A or B
def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]
passed_df = pandas_filter_pass(df)

#Save all results
#Wide marks table with grades
df_output = df[['Name'] + subjects + ['Total', 'Scaled Score', 'Grade']]
df_output.to_csv("problem3_student_wise_marks.csv", index=False)

#Sorted by score
sorted_df.to_csv("problem3_sorted_by_score.csv", index=False)

#Subject averages
subject_avg.to_csv("problem3_subject_averages.csv")

#A/B grade filter
passed_df.to_csv("problem3_passed_students.csv", index=False)

#Optional print summary
print("3 .Student Data (10 Students × 10 Subjects):\n")
print(df_output.to_string(index=False))

print("\nStudents Sorted by Scaled Score:\n")
print(sorted_df[['Name', 'Scaled Score', 'Grade']].to_string(index=False))

print("\nSubject-wise Average Scores:\n")
print(subject_avg)

print("\nStudents with Grade A or B:\n")
print(passed_df[['Name', 'Scaled Score', 'Grade']].to_string(index=False))

3 .Student Data (10 Students × 10 Subjects):

    Name  Maths  Pharmacology  CS  Phsycology  Physiology  Medicine  Chemistry  Physics  Biology  Mechanics  Total  Scaled Score Grade
    Abhi     60            66  66          86          56        94         84       82       59         53    706          70.6     C
   Gagan     54            61  71          50          64        64         82       64       76         75    661          66.1     D
 Lakshmi     68           100  69          64          54        75         74       96       51         72    723          72.3     C
     Ras     60            77  84          72          75        91         57       67       59         93    735          73.5     C
   Vishu     83            69  71          51          52        65         77       85       86         82    721          72.1     C
Shivteja     82            70  97          84          94        87         87       52       88         83    824          82.4     B
   Molly 

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Positive Reviews
positive_reviews = [
    "Absolutely loved the storyline and performances!",
    "An emotional rollercoaster — in the best way!",
    "The cinematography and music were breathtaking.",
    "Brilliant acting and an unforgettable script.",
    "One of the best movies I've seen in years.",
    "A beautifully crafted film with a powerful message.",
    "Outstanding direction and top-notch editing.",
    "It kept me engaged from start to finish.",
    "A masterpiece — pure cinema magic.",
    "Spectacular visuals and strong character development."
]

# Negative Reviews
negative_reviews = [
    "The plot was weak and painfully slow.",
    "Terrible acting ruined an already bad script.",
    "I couldn’t finish it — a total waste of time.",
    "Predictable storyline and flat characters.",
    "Boring and uninspired. I expected more.",
    "Disappointing from such a well-known director.",
    "The dialogues were cringe-worthy.",
    "Overhyped and underdelivered.",
    "Nothing made sense, and it dragged on forever.",
    "It tried to be deep but ended up confusing and dull."
]

# Combine and label
positive_reviews = positive_reviews * 5  # 10 × 5 = 50
negative_reviews = negative_reviews * 5  # 10 × 5 = 50
reviews = positive_reviews + negative_reviews
sentiments = ['positive'] * len(positive_reviews) + ['negative'] * len(negative_reviews)

# Create DataFrame
df = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})

# Vectorize using CountVectorizer
vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(df['Review'])
y = df['Sentiment']

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Naive Bayes classifier
model = MultinomialNB()
model.fit(X_train, y_train)

# Evaluate model
y_pred = model.predict(X_test)
print("Accuracy on test set:", accuracy_score(y_test, y_pred))

# Prediction function
def predict_review_sentiment(model, vectorizer, review):
    review_vec = vectorizer.transform([review])
    return model.predict(review_vec)[0]

# Test the function
test_review = "I really enjoyed the acting and visuals."
print("Review:", test_review)
print("Predicted Sentiment:", predict_review_sentiment(model, vectorizer, test_review))


Accuracy on test set: 1.0
Review: I really enjoyed the acting and visuals.
Predicted Sentiment: positive


In [ ]:
import pandas as pd
import random
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Positive product review templates
positive_templates = [
    "Absolutely love this product!",
    "Exceeded my expectations — highly recommended.",
    "Build quality is excellent.",
    "Very effective and easy to use.",
    "Fantastic performance for the price.",
    "Reliable and well-designed.",
    "Customer service was top-notch.",
    "Fast delivery and great packaging.",
    "The features are exactly what I needed.",
    "Best purchase I've made this year!"
]

# Negative product review templates
negative_templates = [
    "Terrible experience, not worth the money.",
    "Completely stopped working after a week.",
    "The product was damaged when delivered.",
    "Very poor quality materials used.",
    "It did not match the description.",
    "Not satisfied — it feels cheap and unreliable.",
    "Customer service was unhelpful.",
    "Too expensive for the value it offers.",
    "Instructions were unclear and confusing.",
    "Waste of money — would not recommend."
]

# Generate 50 positive and 50 negative reviews
positive_reviews = random.choices(positive_templates, k=50)
negative_reviews = random.choices(negative_templates, k=50)

reviews = positive_reviews + negative_reviews
labels = ['good'] * 50 + ['bad'] * 50

# Shuffle the dataset
data = list(zip(reviews, labels))
random.shuffle(data)
reviews, labels = zip(*data)

# Create DataFrame
df = pd.DataFrame({
    "Review": reviews,
    "Label": labels
})

# TF-IDF Vectorization
tfidf = TfidfVectorizer(max_features=300, stop_words='english')
X = tfidf.fit_transform(df['Review'])
y = df['Label']

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Logistic Regression Model
model = LogisticRegression()
model.fit(X_train, y_train)

# Evaluate
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Text preprocessing and vectorization function
def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)

# Test Prediction
sample = "This product is amazing and works perfectly!"
vectorized_sample = text_preprocess_vectorize([sample], tfidf)
print("Sample Prediction:", model.predict(vectorized_sample)[0])
print("Vectorized shape:", text_preprocess_vectorize(["This product is amazing and works perfectly!"], tfidf_vectorizer).shape)


Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

         bad       1.00      1.00      1.00        13
        good       1.00      1.00      1.00        12

    accuracy                           1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25

Sample Prediction: good
Vectorized shape: (1, 6)
